### ISSUE TITLE
Multiline HTML with brackets raises Zmpl.SynaxError

### ISSUE THREAD

**Issue by mitteneer** [jetzig-framework/zmpl#17]
The following code will give the `Zmpl.SyntaxError` "Error resolving braces" when placed in a `.zmpl` file.

```
<style>
#myHeader {
  background-color: lightblue;
  color: black;
  padding: 40px;
  text-align: center;
}
</style>
```

I can condense it into one line and it works fine, although requiring everything be condensed into one line seems like it could be a problem (specifically with JavaScript)

**Comment by bobf** [comment]
@mitteneer Thanks for reporting this, I've been trying to think of the best way to deal with it.

I think I'll just disable interpolation inside `<style>` and `<script>` tags, but it's not ideal.

For now, a workaround is to bring the closing brace up to the previous line, like this:
```html
<style>
#myHeader {
  background-color: lightblue;
  color: black;
  padding: 40px;
  text-align: center; }
</style>
```

I'll see if I can get a proper fix done tonight, will update you once I've got something I'm happy with.

**Comment by bobf** [comment]
@mitteneer Sorry it took so long to fix this - I had a hacky fix that would have worked in most cases but I'm glad I didn't rush it as the fix I have now has made the Zmpl parser a lot better.

Braces are now ignored completely unless you're inside a mode block, e.g.:
```zig
@zig {
   // braces are important here
}
```
If you really need to use braces inside a mode block, you can now use a custom heredoc-like delimiter - here's an example from the tests:
```zig
@markdown MARKDOWN
  # Built-in markdown support

  * [jetzig.dev](https://www.jetzig.dev/)
  @zig ZIG
    if (true) {
      @html HTML
        <script>
          const foo = () => {
            console.log("hello");
          };
        </script>
      HTML
    }
  ZIG
MARKDOWN
```
Nice thing is this is not a breaking change, but gives you options to use custom delimiters if you really need to do something unusual, otherwise 99% of cases you can just write regular HTML and it will work as expected. Let me know if you have any issues and thank you for reporting ! I'll get this merged into mainline Jetzig right after sending this comment. : )

**Comment by mitteneer** [comment]
Awesome! Thanks for what you're doing, this is really cool stuff 👍
